#!/usr/bin/env python3
"""Generate agent/shared_libraries/policy_data.py from policy markdown files.

Run after editing any policy .md file:
    python data/policies/generate_policy_constants.py
"""

import os
import sys
import textwrap

import yaml

POLICY_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.normpath(
    os.path.join(POLICY_DIR, "..", "..", "agent", "shared_libraries", "policy_data.py")
)


def parse_frontmatter(content: str) -> tuple[dict, str]:
    if not content.startswith("---"):
        return {}, content
    end = content.index("---", 3)
    fm = yaml.safe_load(content[3:end].strip()) or {}
    body = content[end + 3:].strip()
    return fm, body


def main():
    policies = {}
    merged_thresholds = {}

    for fname in sorted(os.listdir(POLICY_DIR)):
        if not fname.endswith(".md"):
            continue
        with open(os.path.join(POLICY_DIR, fname)) as f:
            content = f.read()
        fm, body = parse_frontmatter(content)
        thresholds = fm.get("thresholds", {})
        policies[fname] = {"thresholds": thresholds, "body": body}
        merged_thresholds.update(thresholds)

    lines = [
        '"""Pre-parsed policy data — generated by data/policies/generate_policy_constants.py."""',
        "",
        "",
    ]

    lines.append("POLICIES = {")
    for fname, data in policies.items():
        lines.append(f"    {fname!r}: {{")
        lines.append(f"        \"thresholds\": {data['thresholds']!r},")
        lines.append(f"        \"body\": {data['body']!r},")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append(f"MERGED_THRESHOLDS = {merged_thresholds!r}")
    lines.append("")

    with open(OUTPUT, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {OUTPUT} with {len(policies)} policies")


if __name__ == "__main__":
    main()
